name:                cloud-haskell
version:             0.1.0.0
github:              "githubuser/cloud-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/cloud-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- distributed-process
- distributed-process-simplelocalnet
- network-transport-tcp
- rank1dynamic
- conduit-combinators
- conduit
- conduit-extra
- text
- distributed-static
- binary
- bytestring
- hw-kafka-client
- hw-kafka-conduit
- hashable
- containers

library:
  source-dirs: src

executables:
  cloud-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cloud-haskell

tests:
  cloud-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cloud-haskell
